### PR TITLE
Added escaping functions to text output - small-content.php

### PR DESCRIPTION
**Pull request by shamalisulakhe**
In ref to PR https://github.com/umer2001/wp-saybers/pull/4

@umer2001 Creating separate PR for each template file so that more changes can be added in the respective PR.

### CODE REVIEW

**Comment by umer2001** [comment]
@shamalisulakhe So, you are going to add more changes in these 4 PRs ?
if yes, please add and if possible take a look at the issue #1. 
when ready let me know, I will merge them :blush:
And thankyou again for contributing in my repo :blue_heart:

**Comment by shamalisulakhe** [comment]
@umer2001 Checked issue #1 
For all the templates I added PR for, there seems no need for sanitizing function. We have already added escaping functions. So that's all for now.
You can merge these PRs as all the text strings in the respective templates have been escaped.

**Comment by umer2001** [comment]
@shamalisulakhe ok I am merging these but sanitizing inputs is also important if we want to make a theme that meets the standards set by wordpress community.

**Comment by shamalisulakhe** [comment]
Agree, sanitizing inputs is important, but it's for the input variables, not for hardcoded strings in the theme templates.

**Comment by umer2001** [comment]
@shamalisulakhe yes, I was also talking about inputs in the issue #1 .

**Pull request merged**
